GET http://localhost:3003/user
Content-Type: application/json

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "João Pedro Lunkes",
    "email": "jp.lunkes@gmail.com",
    "password": "545iuhiuh"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "jp.lunkes@gmail.com",
    "password": "545iuhiuh"
}

###

GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJjZjFiYjdmLTRkZjMtNGI5Ni1hOGUwLTA5MDYyMDZlM2E5MCIsImlhdCI6MTY3NTIxNDA5MiwiZXhwIjoxNjc1MzAwNDkyfQ.jO8NT0wgeN4uR5h4BrWiYl-r73WuVskAzkxnORUGnl4
Content-Type: application/json